2022-06-20 22:44:49,021	INFO head.py:99 -- Dashboard head grpc address: 0.0.0.0:46305
2022-06-20 22:44:49,163	INFO utils.py:99 -- Get all modules by type: DashboardHeadModule
2022-06-20 22:45:23,944	WARNING tune_head.py:23 -- tune module is not available: ray.tune in ray > 0.7.5 requires 'tabulate'. Please re-run 'pip install ray[tune]' or 'pip install ray[rllib]'.
2022-06-20 22:45:24,017	INFO utils.py:132 -- Available modules: [<class 'ray.dashboard.modules.actor.actor_head.ActorHead'>, <class 'ray.dashboard.modules.event.event_head.EventHead'>, <class 'ray.dashboard.modules.job.job_head.JobHead'>, <class 'ray.dashboard.modules.log.log_head.LogHead'>, <class 'ray.dashboard.modules.log.log_head.LogHeadV1'>, <class 'ray.dashboard.modules.node.node_head.NodeHead'>, <class 'ray.dashboard.modules.reporter.reporter_head.ReportHead'>, <class 'ray.dashboard.modules.serve.serve_head.ServeHead'>, <class 'ray.dashboard.modules.snapshot.snapshot_head.APIHead'>, <class 'ray.dashboard.modules.state.state_head.StateHead'>, <class 'ray.dashboard.modules.tune.tune_head.TuneController'>, <class 'ray.dashboard.modules.usage_stats.usage_stats_head.UsageStatsHead'>]
2022-06-20 22:45:24,017	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.actor.actor_head.ActorHead'>
2022-06-20 22:45:24,033	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.event.event_head.EventHead'>
2022-06-20 22:45:24,033	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.job.job_head.JobHead'>
2022-06-20 22:45:24,033	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.log.log_head.LogHead'>
2022-06-20 22:45:24,143	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.log.log_head.LogHeadV1'>
2022-06-20 22:45:24,143	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.node.node_head.NodeHead'>
2022-06-20 22:45:24,143	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.reporter.reporter_head.ReportHead'>
2022-06-20 22:45:24,143	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.serve.serve_head.ServeHead'>
2022-06-20 22:45:24,144	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.snapshot.snapshot_head.APIHead'>
2022-06-20 22:45:24,144	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.state.state_head.StateHead'>
2022-06-20 22:45:24,144	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.tune.tune_head.TuneController'>
2022-06-20 22:45:24,144	INFO head.py:161 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.usage_stats.usage_stats_head.UsageStatsHead'>
2022-06-20 22:45:25,783	INFO head.py:165 -- Loaded 12 modules.
2022-06-20 22:45:25,821	INFO http_server_head.py:61 -- Setup static dir for dashboard: /mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/client/build
2022-06-20 22:45:25,827	INFO http_server_head.py:132 -- Dashboard head http address: 127.0.0.1:8265
2022-06-20 22:45:25,827	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /logical/actor_groups> -> <function ActorHead.get_actor_groups at 0x7f271a1a5440>
2022-06-20 22:45:25,827	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /logical/actors> -> <function ActorHead.get_all_actors[cache ttl=2, max_size=128] at 0x7f271a1a55f0>
2022-06-20 22:45:25,827	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /logical/kill_actor> -> <function ActorHead.kill_actor at 0x7f271a1a57a0>
2022-06-20 22:45:25,827	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /events> -> <function EventHead.get_event[cache ttl=2, max_size=128] at 0x7f2719e6f950>
2022-06-20 22:45:25,827	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/version> -> <function JobHead.get_version at 0x7f2719e88680>
2022-06-20 22:45:25,827	INFO http_server_head.py:137 -- <ResourceRoute [GET] <DynamicResource  /api/packages/{protocol}/{package_name}> -> <function JobHead.get_package at 0x7f2719e8c3b0>
2022-06-20 22:45:25,827	INFO http_server_head.py:137 -- <ResourceRoute [PUT] <DynamicResource  /api/packages/{protocol}/{package_name}> -> <function JobHead.upload_package at 0x7f2719e8c560>
2022-06-20 22:45:25,827	INFO http_server_head.py:137 -- <ResourceRoute [POST] <PlainResource  /api/jobs/> -> <function JobHead.submit_job at 0x7f2719e8c710>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [POST] <DynamicResource  /api/jobs/{job_id}/stop> -> <function JobHead.stop_job at 0x7f2719e8c8c0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <DynamicResource  /api/jobs/{job_id}> -> <function JobHead.get_job_info at 0x7f2719e8ca70>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/jobs/> -> <function JobHead.list_jobs at 0x7f2719e8cc20>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <DynamicResource  /api/jobs/{job_id}/logs> -> <function JobHead.get_job_logs at 0x7f2719e8cdd0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <DynamicResource  /api/jobs/{job_id}/logs/tail> -> <function JobHead.tail_job_logs at 0x7f2719e8cf80>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /log_index> -> <function LogHead.get_log_index at 0x7f2719e20b00>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /log_proxy> -> <function LogHead.get_log_from_proxy at 0x7f2719e20c20>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/experimental/logs/list> -> <function LogHeadV1.handle_list_logs at 0x7f2719e23200>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /nodes> -> <function NodeHead.get_all_nodes[cache ttl=2, max_size=128] at 0x7f2719e295f0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <DynamicResource  /nodes/{node_id}> -> <function NodeHead.get_node[cache ttl=2, max_size=128] at 0x7f2719e29830>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /memory/memory_table> -> <function NodeHead.get_memory_table at 0x7f2719e299e0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /memory/set_fetch> -> <function NodeHead.set_fetch_memory_info at 0x7f2719e29b00>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /node_logs> -> <function NodeHead.get_logs at 0x7f2719e29c20>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /node_errors> -> <function NodeHead.get_errors at 0x7f2719e29d40>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/launch_profiling> -> <function ReportHead.launch_profiling at 0x7f2719b92dd0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/ray_config> -> <function ReportHead.get_ray_config at 0x7f2719b92ef0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/cluster_status> -> <function ReportHead.get_cluster_status at 0x7f2719b97050>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/serve/deployments/> -> <function ServeHead.get_all_deployments at 0x7f2719bb2ef0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/serve/deployments/status> -> <function ServeHead.get_all_deployment_statuses at 0x7f2719bb30e0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [DELETE] <PlainResource  /api/serve/deployments/> -> <function ServeHead.delete_serve_application at 0x7f2719bb3290>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [PUT] <PlainResource  /api/serve/deployments/> -> <function ServeHead.put_all_deployments at 0x7f2719bb3440>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/actors/kill> -> <function APIHead.kill_actor_gcs at 0x7f2719bbb320>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/snapshot> -> <function APIHead.snapshot at 0x7f2719bbb440>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/v0/actors> -> <function StateHead.list_actors at 0x7f2719b5f440>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/v0/jobs> -> <function StateHead.list_jobs at 0x7f2719b5f560>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/v0/nodes> -> <function StateHead.list_nodes at 0x7f2719b5f680>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/v0/placement_groups> -> <function StateHead.list_placement_groups at 0x7f2719b5f7a0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/v0/workers> -> <function StateHead.list_workers at 0x7f2719b5f8c0>
2022-06-20 22:45:25,828	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/v0/tasks> -> <function StateHead.list_tasks at 0x7f2719b5f9e0>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /api/v0/objects> -> <function StateHead.list_objects at 0x7f2719b5fb00>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /tune/info> -> <function TuneController.tune_info at 0x7f2719b77560>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /tune/availability> -> <function TuneController.get_availability at 0x7f2719b77200>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /tune/set_experiment> -> <function TuneController.set_tune_experiment at 0x7f2719b774d0>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /tune/enable_tensorboard> -> <function TuneController.enable_tensorboard at 0x7f2719b775f0>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /usage_stats_enabled> -> <function UsageStatsHead.get_usage_stats_enabled at 0x7f270f7555f0>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/tmp/ray/session_2022-06-20_22-44-31_837319_128819/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/tmp/ray/session_2022-06-20_22-44-31_837319_128819/logs')>>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /> -> <function HttpServerDashboardHead.get_index at 0x7f270f6dab00>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <PlainResource  /favicon.ico> -> <function HttpServerDashboardHead.get_favicon at 0x7f2719b6ddd0>
2022-06-20 22:45:25,829	INFO http_server_head.py:137 -- <ResourceRoute [GET] <StaticResource  /static -> PosixPath('/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/client/build/static')> -> <bound method StaticResource._handle of <StaticResource  /static -> PosixPath('/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/client/build/static')>>
2022-06-20 22:45:25,829	INFO http_server_head.py:138 -- Registered 47 routes.
2022-06-20 22:45:25,830	INFO datacenter.py:70 -- Purge data.
2022-06-20 22:45:25,862	INFO event_utils.py:127 -- Monitor events logs modified after 1655734493.1192133 on /tmp/ray/session_2022-06-20_22-44-31_837319_128819/logs/events, the source types are ['GCS'].
2022-06-20 22:45:26,129	INFO usage_stats_head.py:108 -- Usage reporting is enabled.
2022-06-20 22:45:26,130	INFO actor_head.py:102 -- Getting all actor info from GCS.
2022-06-20 22:45:26,492	INFO actor_head.py:128 -- Received 0 actor info from GCS.
2022-06-20 22:45:44,465	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736343.569168138","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:46:13,810	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736373.326893891","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:46:39,074	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736396.246526565","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
>
2022-06-20 22:46:48,234	INFO usage_stats_head.py:77 -- Usage report request failed. HTTPSConnectionPool(host='usage-stats.ray.io', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f270c6010d0>, 'Connection to usage-stats.ray.io timed out. (connect timeout=10)'))
2022-06-20 22:47:37,475	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736454.091517071","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:47:54,811	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736474.787707556","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:48:13,571	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736493.556544779","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:48:18,610	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736498.610537769","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:48:55,899	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736535.861546706","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:48:59,040	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736539.040542509","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:49:14,676	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736553.435012281","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:49:34,152	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736574.137540648","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:50:16,620	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736616.056170212","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:50:19,927	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736619.643539035","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:50:34,675	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736633.279537008","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:50:51,705	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736651.616542943","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:50:54,183	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736654.183081407","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:51:15,614	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736675.457679173","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:51:18,651	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736678.651535586","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:51:36,546	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736695.397968534","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:51:39,609	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736699.564538911","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:51:59,029	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736716.420958859","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:52:26,944	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736746.917560572","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:52:46,033	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736765.593696514","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:53:13,635	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736793.616545800","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:53:49,659	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736828.046957134","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:54:15,595	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736854.420550805","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:54:37,609	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736877.590539486","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:54:59,413	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736898.196095776","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:55:04,044	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736904.027551595","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:55:29,015	INFO datacenter.py:70 -- Purge data.
2022-06-20 22:55:30,051	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736929.841574094","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:55:50,973	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736950.061110229","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:56:31,681	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655736988.391163766","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:56:48,907	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655737007.569971200","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:57:45,258	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655737064.175440825","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:58:18,135	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655737098.100413950","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:58:35,655	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655737115.641550881","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:58:57,560	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655737137.546556700","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
2022-06-20 22:59:37,906	ERROR node_head.py:259 -- Error updating node stats of 7562cb0081c73f4ed2ac21d1956887bd794b724f1b8c157f4e02d603.
Traceback (most recent call last):
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/ray/dashboard/modules/node/node_head.py", line 254, in _update_node_stats
    timeout=2,
  File "/mnt/lustre/zhangyuchang/.conda/envs/0524alpa/lib/python3.7/site-packages/grpc/aio/_call.py", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1655737177.888558363","description":"Error received from peer ipv4:10.140.1.109:40043","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
